import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // Import your Navbar
import FooterSection from "@/components/FooterSection"; // Import your Footer
import PreLoader from "@/components/PreLoader"; // Import your PreLoader

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Abhishek Dhupar Films",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PreLoader />
        <Navbar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}